services:
  - type: web
    name: traffic-telligence-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd Flask && gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
